//---------------------------------------------------------------------------
//   Arquivo de chave RSA 1024
//   Gravado em [C:\TQSAPP\LINK\APLIC\LINK\TQSProt\LINK_EXE_CPU.H] em 18-11-2025 20:38:43
//   Pelo programa TQSASSIN.EXE
//   Chave p\xfablica correspondente ao arquivo [C:\TQSAPP\LINK\APLIC\LINK\TQSProt\LINK.EXE]
//---------------------------------------------------------------------------
unit LINK_EXE_CPU;
interface
uses APLICTQS;
var
glb_chapubl: TChave = (
	$30, $81, $9D, $30, $0D, $06, $09, $2A, $86, $48,
	$86, $F7, $0D, $01, $01, $01, $05, $00, $03, $81,
	$8B, $00, $30, $81, $87, $02, $81, $81, $00, $9D,
	$8E, $F8, $7A, $C9, $04, $02, $F8, $26, $48, $DB,
	$A0, $ED, $1A, $59, $48, $19, $89, $B6, $24, $26,
	$26, $6E, $FF, $90, $DD, $F5, $63, $C2, $9C, $76,
	$FA, $C1, $46, $A6, $32, $BD, $E3, $6F, $B9, $F0,
	$7E, $28, $E2, $79, $92, $24, $A3, $0D, $4B, $5B,
	$D0, $6A, $5F, $CC, $1C, $A0, $77, $89, $25, $13,
	$3B, $69, $C6, $82, $42, $1E, $32, $67, $A8, $B2,
	$8D, $BC, $1A, $EC, $D9, $FD, $D4, $E6, $AF, $9C,
	$94, $A2, $B0, $F1, $45, $55, $B6, $A5, $22, $9B,
	$6F, $0B, $C3, $97, $5B, $67, $84, $48, $BE, $82,
	$CB, $F6, $5B, $A9, $FC, $4D, $F8, $CA, $3A, $C3,
	$C2, $52, $FB, $FE, $66, $98, $70, $6E, $57, $72,
	$B2, $24, $6A, $EB, $54, $BC, $9D, $02, $01, $11
    );
implementation
end.
